### ISSUE TITLE
Traiter les séries journalières climatiques avant 1980

### ISSUE THREAD

**Issue by jnsebgosselin** [cgq-qgc/pacc-inrs#27]
Dans une première étape, les données climatiques ont été comblées de 1980 à aujourd'hui. 

Toutefois, il serait nécessaire d'avoir les données traitées avant 1980 car cela est important dans les études de relations statistiques entre les différentes séries temporelles.

-> Il serait également important de documenter la méthodologie qui a été suivie pour combler les données manquantes dans les séries temporelles.

**Comment by x-malet** [comment]
Ne pas oublier de faire en sorte que l'encodage soit en UTF-8

**Comment by jnsebgosselin** [comment]
Ok donc je peux fermer cette issue car les données avant 1980 n'ont pas et ne seront pas utilisées dans le cadre du projet.
